## Importing libraries:

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

## Load dataset:

In [ ]:
df=pd.read_csv(r"Data/Iris.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\DecodeLab Internship\\Project_2_Iris_Model\\Data\\Iris.csv'

In [ ]:
df.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

#### Encoding values:
- Encoding species column values beacause model cann't understand string values we have to convert this to numeric values.

In [ ]:
le=LabelEncoder()   # instance of class labelencoder()
df["Species_en"]=le.fit_transform(df["Species"]) 
# Works only before dropping 'Species'

In [ ]:
df = df.drop(columns="Species")  
df = df.drop(columns="Id")
# Remove categorical column before training

In [ ]:
df.head()  # Verify encoding result

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species_en
0            5.1           3.5            1.4           0.2           0
1            4.9           3.0            1.4           0.2           0
2            4.7           3.2            1.3           0.2           0
3            4.6           3.1            1.5           0.2           0
4            5.0           3.6            1.4           0.2           0

## Split Data:

#### Split Data into input variables and target variables:

In [ ]:
x = df.drop(columns="Species_en")  # x = input variables or feature
y = df["Species_en"] # y = target variables or labeled

#### Split into train and test data:

In [ ]:
x_train,x_test, y_train, y_test =train_test_split(x,y,test_size=0.2,random_state=42)

## Training model:

In [ ]:
model = LogisticRegression(max_iter=1000)   # model instance of logisticRegression

In [ ]:
model.fit(x_train,y_train)   # model training on x_train,y_train

LogisticRegression(max_iter=1000)

## Checking Accuracy:

In [ ]:
y_pred = model.predict(x_test)   # find predictions and store in variables. mean we find result of model on x test.

In [ ]:
accuracy = accuracy_score(y_test, y_pred)

In [ ]:
print(accuracy)   # accuracy is 1.0 mean 100% accurate.

1.0

## Prediction:

In [ ]:
print(x_test)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
73             6.1           2.8            4.7           1.2
18             5.7           3.8            1.7           0.3
118            7.7           2.6            6.9           2.3
78             6.0           2.9            4.5           1.5
76             6.8           2.8            4.8           1.4
31             5.4           3.4            1.5           0.4
64             5.6           2.9            3.6           1.3
141            6.9           3.1            5.1           2.3
68             6.2           2.2            4.5           1.5
82             5.8           2.7            3.9           1.2
110            6.5           3.2            5.1           2.0
12             4.8           3.0            1.4           0.1
36             5.5           3.5            1.3           0.2
9              4.9           3.1            1.5           0.1
19             5.1           3.8            1.5           0.3
56             6.3           3.3            4.7           1.6
104            6.5           3.0            5.8           2.2
69             5.6           2.5            3.9           1.1
55             5.7           2.8            4.5           1.3
132            6.4           2.8            5.6           2.2
29             4.7           3.2            1.6           0.2
127            6.1           3.0            4.9           1.8
26             5.0           3.4            1.6           0.4
128            6.4           2.8            5.6           2.1
131            7.9           3.8            6.4           2.0
145            6.7           3.0            5.2           2.3
108            6.7           2.5            5.8           1.8
143            6.8           3.2            5.9           2.3
45             4.8           3.0            1.4           0.3
30             4.8           3.1            1.6           0.2

In [ ]:
model.predict([[6.1,2.8,4.7,1.2]])  # Predict class using trained model for a single input sample

c:\Users\pc\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])

In [ ]:
sample1 =pd.DataFrame([[6.1,2.8,4.7,1.2]], columns=[ 'SepalLengthCm', 'SepalWidthCm' , 'PetalLengthCm' , 'PetalWidthCm'])
# Create a sample input DataFrame with feature names for prediction

model.predict(sample1)

array([1])

## Comparison of Actual Vs Prediction:

In [ ]:
result= pd.DataFrame({
    "actual": y_test,
    "predict": y_pred
})
# Create a DataFrame to compare actual values with model predictions side by side

print(result)

     actual  predict
73        1        1
18        0        0
118       2        2
78        1        1
76        1        1
31        0        0
64        1        1
141       2        2
68        1        1
82        1        1
110       2        2
12        0        0
36        0        0
9         0        0
19        0        0
56        1        1
104       2        2
69        1        1
55        1        1
132       2        2
29        0        0
127       2        2
26        0        0
128       2        2
131       2        2
145       2        2
108       2        2
143       2        2
45        0        0
30        0        0

## Conclusion
- From accuracy evaluation and comparison of actual vs predicted values, we conclude that the model is successfully trained.

## Save the Model:
- After training model, we don’t want to train it again and again.
- So we save it once, then later we can use it anytime.
- For saving model we have to import joblib.
- Joblib library use fro saving models.

In [ ]:
import pickle

In [ ]:
with open("model.pkl","wb") as f:
    pickle.dump(model, f) # dump is method of joblib which save model as model.pkl file

- model saved successfuly.

#### Converting trained model into a web page for analysis.